package model

import (
	"context"
	"errors"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var ErrInvalidRouteShadowObservation = errors.New("invalid route shadow observation")

var routeShadowObservationCounterColumns = []string{
	"shadow_decisions",
	"shadow_initial_decisions",
	"shadow_diffs",
	"capability_resolved",
	"capability_unresolved",
	"mapping_conflict",
	"unknown_filtered",
	"unknown_admitted",
	"mixed_decisions",
	"unauthorized_filtered",
	"unauthorized_admitted",
	"snapshot_stale",
	"event_attempted",
	"event_enqueued",
	"event_dropped",
	"event_encode_failed",
	"event_submitted",
	"event_write_failed",
	"refresh_success",
	"refresh_failure",
	"snapshot_conflict",
	"refresh_lag_count",
	"refresh_lag_le_1s",
	"refresh_lag_le_5s",
	"refresh_lag_le_15s",
	"refresh_lag_le_30s",
	"refresh_lag_le_60s",
	"refresh_lag_le_120s",
	"refresh_lag_le_300s",
	"refresh_lag_gt_300s",
}

// UpsertRouteShadowHourlyObservations adds low-cardinality deltas under a
// database transaction. The insert-ignore plus arithmetic update pattern is
// generated by GORM for SQLite, MySQL, and PostgreSQL without relying on a
// database-specific UPSERT expression.
func UpsertRouteShadowHourlyObservations(ctx context.Context, deltas []RouteShadowHourlyObservation) error {
	if len(deltas) == 0 {
		return nil
	}
	if DB == nil {
		return errors.New("route shadow observation database is unavailable")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	now := time.Now().Unix()
	return DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, delta := range deltas {
			if !validRouteShadowObservationDelta(delta) {
				return ErrInvalidRouteShadowObservation
			}
			stub := RouteShadowHourlyObservation{
				HourStart:  delta.HourStart,
				InstanceID: delta.InstanceID,
				Scope:      delta.Scope,
				ModelName:  delta.ModelName,
				UpdatedAt:  now,
			}
			if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&stub).Error; err != nil {
				return err
			}

			updates := routeShadowObservationUpdates(delta, now)
			result := tx.Model(&RouteShadowHourlyObservation{}).
				Where("hour_start = ? AND instance_id = ? AND scope = ? AND model_name = ? AND sealed_at = ?", delta.HourStart, delta.InstanceID, delta.Scope, delta.ModelName, 0).
				Updates(updates)
			if result.Error != nil {
				return result.Error
			}
			if result.RowsAffected > 0 {
				continue
			}

			// A late delta must never change a sealed hour. Marking it incomplete
			// makes diagnostics reject the window instead of reporting a partial
			// result as valid evidence.
			var existing RouteShadowHourlyObservation
			if err := tx.Select("id", "sealed_at").
				Where("hour_start = ? AND instance_id = ? AND scope = ? AND model_name = ?", delta.HourStart, delta.InstanceID, delta.Scope, delta.ModelName).
				First(&existing).Error; err != nil {
				return err
			}
			if existing.SealedAt > 0 {
				if err := tx.Model(&RouteShadowHourlyObservation{}).Where("id = ?", existing.ID).
					Updates(map[string]interface{}{"data_loss_possible": true, "updated_at": now}).Error; err != nil {
					return err
				}
			}
		}
		return nil
	})
}

func validRouteShadowObservationDelta(delta RouteShadowHourlyObservation) bool {
	if delta.HourStart <= 0 || strings.TrimSpace(delta.InstanceID) == "" {
		return false
	}
	if delta.Scope != RouteShadowObservationGlobal && delta.Scope != RouteShadowObservationModel {
		return false
	}
	if delta.Scope == RouteShadowObservationGlobal {
		return delta.ModelName == ""
	}
	return strings.TrimSpace(delta.ModelName) != ""
}

func routeShadowObservationUpdates(delta RouteShadowHourlyObservation, now int64) map[string]interface{} {
	updates := map[string]interface{}{
		"updated_at": now,
	}
	for _, column := range routeShadowObservationCounterColumns {
		updates[column] = gorm.Expr(column+" + ?", routeShadowObservationCounterValue(delta, column))
	}
	if delta.DataLossPossible {
		updates["data_loss_possible"] = true
	}
	return updates
}

func routeShadowObservationCounterValue(delta RouteShadowHourlyObservation, column string) int64 {
	switch column {
	case "shadow_decisions":
		return delta.ShadowDecisions
	case "shadow_initial_decisions":
		return delta.ShadowInitialDecisions
	case "shadow_diffs":
		return delta.ShadowDiffs
	case "capability_resolved":
		return delta.CapabilityResolved
	case "capability_unresolved":
		return delta.CapabilityUnresolved
	case "mapping_conflict":
		return delta.MappingConflict
	case "unknown_filtered":
		return delta.UnknownFiltered
	case "unknown_admitted":
		return delta.UnknownAdmitted
	case "mixed_decisions":
		return delta.MixedDecisions
	case "unauthorized_filtered":
		return delta.UnauthorizedFiltered
	case "unauthorized_admitted":
		return delta.UnauthorizedAdmitted
	case "snapshot_stale":
		return delta.SnapshotStale
	case "event_attempted":
		return delta.EventAttempted
	case "event_enqueued":
		return delta.EventEnqueued
	case "event_dropped":
		return delta.EventDropped
	case "event_encode_failed":
		return delta.EventEncodeFailed
	case "event_submitted":
		return delta.EventSubmitted
	case "event_write_failed":
		return delta.EventWriteFailed
	case "refresh_success":
		return delta.RefreshSuccess
	case "refresh_failure":
		return delta.RefreshFailure
	case "snapshot_conflict":
		return delta.SnapshotConflict
	case "refresh_lag_count":
		return delta.RefreshLagCount
	case "refresh_lag_le_1s":
		return delta.RefreshLagLE1S
	case "refresh_lag_le_5s":
		return delta.RefreshLagLE5S
	case "refresh_lag_le_15s":
		return delta.RefreshLagLE15S
	case "refresh_lag_le_30s":
		return delta.RefreshLagLE30S
	case "refresh_lag_le_60s":
		return delta.RefreshLagLE60S
	case "refresh_lag_le_120s":
		return delta.RefreshLagLE120S
	case "refresh_lag_le_300s":
		return delta.RefreshLagLE300S
	case "refresh_lag_gt_300s":
		return delta.RefreshLagGT300S
	default:
		return 0
	}
}

func ListRouteShadowHourlyObservations(ctx context.Context, startHour, endHour int64) ([]RouteShadowHourlyObservation, error) {
	if DB == nil {
		return nil, errors.New("route shadow observation database is unavailable")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	var observations []RouteShadowHourlyObservation
	err := DB.WithContext(ctx).
		Where("hour_start >= ? AND hour_start < ?", startHour, endHour).
		Order("hour_start asc, instance_id asc, scope asc, model_name asc").
		Find(&observations).Error
	return observations, err
}

func SealRouteShadowHourlyObservations(ctx context.Context, instanceID string, beforeHour int64) error {
	if DB == nil {
		return errors.New("route shadow observation database is unavailable")
	}
	if strings.TrimSpace(instanceID) == "" || beforeHour <= 0 {
		return ErrInvalidRouteShadowObservation
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return DB.WithContext(ctx).Model(&RouteShadowHourlyObservation{}).
		Where("instance_id = ? AND hour_start < ? AND sealed_at = ?", instanceID, beforeHour, 0).
		Updates(map[string]interface{}{"sealed_at": time.Now().Unix(), "updated_at": time.Now().Unix()}).Error
}

// SealExpiredRouteShadowHourlyObservations closes observations from every
// instance before the current hour. A restarted instance must be able to seal
// the last hour written by its predecessor, otherwise a benign restart would
// permanently invalidate the seven-day acceptance window.
func SealExpiredRouteShadowHourlyObservations(ctx context.Context, beforeHour int64) error {
	if DB == nil {
		return errors.New("route shadow observation database is unavailable")
	}
	if beforeHour <= 0 {
		return ErrInvalidRouteShadowObservation
	}
	if ctx == nil {
		ctx = context.Background()
	}
	now := time.Now().Unix()
	return DB.WithContext(ctx).Model(&RouteShadowHourlyObservation{}).
		Where("hour_start < ? AND sealed_at = ?", beforeHour, 0).
		Updates(map[string]interface{}{"sealed_at": now, "updated_at": now}).Error
}

func DeleteExpiredRouteShadowHourlyObservations(ctx context.Context, beforeHour int64) error {
	if DB == nil {
		return errors.New("route shadow observation database is unavailable")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return DB.WithContext(ctx).
		Where("hour_start < ? AND sealed_at > ?", beforeHour, 0).
		Delete(&RouteShadowHourlyObservation{}).Error
}
